version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app
      - ./uploads:/app/uploads  # Bind mount for the uploads folder
    #restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    #restart: always
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production

  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro            # Global nginx config
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro # Server block for frontend and backend routing
      - ./gateway/certs:/etc/nginx/ssl:ro                        # SSL certificates
    depends_on:
      - backend
      - frontend

volumes:
  uploads:
