version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app
      - ./uploads:/app/uploads  # Bind mount for the uploads folder
    #restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container
    #restart: always
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production

volumes:
  uploads:
