version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app
      - ./uploads:/app/uploads  # Bind mount for the uploads folder
    #restart: always

volumes:
  uploads:
